version: '3.7'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-data:/data
      - ./redis-stack.conf:/redis-stack.conf

volumes:
  redis-data: